version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: myprofy_backend
    restart: always
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elasticsearch
    command: >
      bash -c "
      python manage.py collectstatic --noinput &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      until curl -s http://elasticsearch:9200 > /dev/null; do
        echo '⏳ Waiting for Elasticsearch...';
        sleep 5;
      done &&
      echo '🚀 Elasticsearch is up, building indexes...' &&
      python manage.py search_index --rebuild -f &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "

  db:
    image: postgres:15
    container_name: myprofy_db
    restart: always
    env_file:
      - backend/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  elasticsearch:
    build:
      context: .
      dockerfile: elasticsearch/Dockerfile
    container_name: myprofy_elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  es_data: