name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            set -euo pipefail

            cd /var/www/Backend

            echo "Fetching latest code..."
            git fetch origin main
            git checkout main
            git reset --hard origin/main
            git clean -fd

            echo "Rebuilding app container (without touching DB)..."
            # Faqat backend service'ni yangilaymiz
            docker compose pull backend || true
            docker compose build backend --pull
            docker compose up -d backend

            echo "Cleaning unused images..."
            docker image prune -f

            echo "Current container status:"
            docker compose ps
