name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            set -euo pipefail

            cd /var/www/Backend

            # Kodni aniq main holatiga olib kelish
            git fetch origin main
            git checkout main
            git reset --hard origin/main
            git clean -fd

            docker compose down
            docker compose pull || true     
            docker compose build --pull
            docker compose up -d
            docker compose ps